### ISSUE TITLE
Izanami client 1.4.0 fails to connect to cloud hosted server

### ISSUE THREAD

**Issue by DraganRaicici** [MAIF/izanami#228]
We have the izanami client running in our service. Our service is running Play 2.7 on Scala 2.12.8.
We included some new dependencies in hopes of squashing some dependency conflict warnings when booting up the service, namely: 

  "com.typesafe.akka"           %% "akka-parsing"                   % "10.1.7",
  "com.typesafe.akka"           %% "akka-http"                         % "10.1.7",
  "com.typesafe.akka"           %% "akka-http-core"                 % "10.1.7"

Upon further inspection, I saw that izanami uses "akka-http" at version 10.1.3, so I also tried changing our dependencies accordingly and the issue still stands.

Basically, having the izanami server (1.4.0) in a dockerized container locally running on localhost:8081 works as expected, but the izanami client fails to communicate to a cloud hosted instance of the izanami client.

Here are parts of our logs:
First, it starts off with some warnings:

``` 
[WARN] [03/08/2019 09:12:48.006] [IzanamiSystem-akka.actor.default-dispatcher-3] [IzanamiSystem/Pool(shared->*cloud hosted server location*:0)] Connection attempt failed. Backing off new connection attempts for at least 100 milliseconds.

[WARN] [03/08/2019 09:12:48.166] [IzanamiSystem-akka.actor.default-dispatcher-3] [IzanamiSystem/Pool(shared->*cloud hosted server location*:0)] Connection attempt failed. Backing off new connection attempts for at least 200 milliseconds. 
```

which then escalate to errors:

```
[ERROR] [03/08/2019 09:15:05.539] [IzanamiSystem-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(IzanamiSystem)] Error during call
akka.stream.BufferOverflowException: Exceeded configured max-open-requests value of [32]. 
This means that the request queue of this pool (HostConnectionPoolSetup(*cloud hosted server location*,0,ConnectionPoolSetup(ConnectionPoolSettings(4,0,5,32,1,100 milliseconds,2 minutes,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.1.7),10 seconds,1 minute,512,None,WebSocketSettings(<function0>,ping,Duration.Inf,akka.http.impl.settings.WebSocketSettingsImpl$$$Lambda$578/0x000000084049e840@4f134fc2),List(),ParserSettings(2048,16,64,64,8192,64,8388608,8388608,256,1048576,Strict,RFC6265,true,Set(),Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,true,akka.util.ConstantFun$$$Lambda$568/0x0000000840470840@630f9c9,akka.util.ConstantFun$$$Lambda$568/0x0000000840470840@630f9c9,akka.util.ConstantFun$$$Lambda$569/0x0000000840498040@1ab1a2a1),None,TCPTransport),New,1 second),akka.http.scaladsl.HttpConnectionContext$@4f09936a,akka.event.MarkerLoggingAdapter@840e350))) has completely filled up because the pool currently does not process requests fast enough to handle the incoming request load. Please retry the request later. See http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html for more information.
at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:88)
at akka.http.impl.engine.client.PoolInterfaceActor$.$anonfun$props$1(PoolInterfaceActor.scala:34)
at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)...

[ERROR] [03/08/2019 09:15:05.540] [IzanamiSystem-akka.actor.default-dispatcher-7] [SmartCacheFeatureClient(akka://IzanamiSystem)] Error fetching features with pattern myfeature:myfeature:*

[ERROR] [03/08/2019 09:15:05.541] [IzanamiSystem-akka.actor.default-dispatcher-10] [SmartCacheStrategyHandler(akka://IzanamiSystem)] Error refreshing cache 
```

We tried using the Fetch strategy at first and then tried the CacheWithPollingStrategy, with the same results.

Another question would be: If online connection fails, how come it doesn't just simply fall back to the fallback configuration?

**Comment by sorenvalentinjp** [comment]
Same as #194
