### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by gmembre-zenika** [MAIF/izanami#243]
I'm trying to compile izanami following the [documentation](https://maif.github.io/izanami/manual/getizanami/fromsources.html) on OSX and it fails with `java.lang.StackOverflowError`.
 
```
> sbt about
[info] Loading project definition from /Users/guillaume/project
[info] Set current project to guillaume (in build file:/Users/guillaume/)
[info] This is sbt 1.2.8
[info] The current project is ProjectRef(uri("file:/Users/guillaume/"), "guillaume") 0.1.0-SNAPSHOT
[info] The current project is built against Scala 2.12.7
[info] Available Plugins
[info]  - sbt.ScriptedPlugin
[info]  - sbt.plugins.CorePlugin
[info]  - sbt.plugins.Giter8TemplatePlugin
[info]  - sbt.plugins.IvyPlugin
[info]  - sbt.plugins.JUnitXmlReportPlugin
[info]  - sbt.plugins.JvmPlugin
[info]  - sbt.plugins.SbtPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.12.7
```
Compiles error : 
```
> sbt 'izanami-server/assembly'                                                                                                                                                                                                  (master|✔)
[info] Loading settings for project izanami-build from plugins.sbt ...
[info] Loading project definition from /Users/guillaume/projets/src/izanami/project
[info] Loading settings for project root from version.sbt,build.sbt ...
[info] Loading settings for project simulation from build.sbt ...
[info] Loading settings for project example from build.sbt ...
[info] Loading settings for project izanami-clients from build.sbt ...
[info] Loading settings for project perfs-jmh from build.sbt ...
[info] Loading settings for project izanami-server from build.sbt ...
[info] Loading settings for project izanami-documentation from build.sbt ...
[info] Loading settings for project example-play from build.sbt ...
[info] Loading settings for project example-spring from build.sbt ...
[info] Loading settings for project jvm from build.sbt ...
[info] Resolving key references (10097 settings) ...
[info] Set current project to izanami (in build file:/Users/guillaume/projets/src/izanami/)
[success] Total time: 5 s, completed Apr 24, 2019, 11:24:50 AM
[info] Compiling 96 Scala sources and 2 Java sources to /Users/guillaume/projets/src/izanami/izanami-server/target/scala-2.12/classes ...
[error] ## Exception when compiling 98 sources to /Users/guillaume/projets/src/izanami/izanami-server/target/scala-2.12/classes
[error] null
[error] scala.reflect.internal.tpe.TypeMaps$ErroneousCollector$.traverse(TypeMaps.scala:1167)
[error] scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:114)
[error] scala.reflect.internal.tpe.TypeMaps$ErroneousCollector$.traverse(TypeMaps.scala:1168)
[error] scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$3(TypeMaps.scala:157)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:216)
[error] scala.reflect.internal.tpe.TypeMaps$ErroneousCollector$.traverse(TypeMaps.scala:1168)
[error] scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:232)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:242)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:246)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:259)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$2(TypeMaps.scala:142)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:216)
[error] scala.reflect.internal.tpe.TypeMaps$ErroneousCollector$.traverse(TypeMaps.scala:1168)
[error] scala.reflect.internal.tpe.TypeMaps$TypeCollector.collect(TypeMaps.scala:335)
[error] scala.reflect.internal.Types$Type.isErroneous(Types.scala:311)
[error] scala.reflect.internal.Trees$TreeContextApiImpl.isErroneous(Trees.scala:203)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$2(Macros.scala:625)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$2$adapted(Macros.scala:625)
[error] scala.reflect.internal.Trees$FindTreeTraverser.traverse(Trees.scala:1696)
[error] scala.reflect.internal.Trees$FindTreeTraverser.traverse(Trees.scala:1692)
[error] scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1316)
[error] scala.reflect.internal.Trees.itraverse(Trees.scala:1366)
[error] scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] scala.reflect.internal.Trees$FindTreeTraverser.traverse(Trees.scala:1697)
[error] scala.reflect.internal.Trees$TreeContextApiImpl.find(Trees.scala:133)
[error] scala.reflect.internal.Trees$TreeContextApiImpl.exists(Trees.scala:137)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:625)
[error] scala.tools.nsc.Global.withInfoLevel(Global.scala:227)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:625)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:612)
[error] scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:787)
[error] scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:785)
[error] scala.tools.nsc.Global$$anon$4.standardMacroExpand(Global.scala:477)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:439)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:436)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:408)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:436)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:436)
[error] scala.tools.nsc.Global$$anon$4.pluginsMacroExpand(Global.scala:477)
[error] scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:776)
[error] scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:769)
[error] scala.tools.nsc.Global$$anon$4.macroExpand(Global.scala:477)
[error] scala.tools.nsc.typechecker.Macros$$anon$4.transform(Macros.scala:966)
[......]
[error] scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
[error] scala.tools.nsc.Global$$anon$4.inferImplicitFor(Global.scala:477)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$applyImplicitArgs$2(Typers.scala:263)
[error] scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:256)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:901)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:491)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1239)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1236)
[error]
[error] java.lang.StackOverflowError
[error] 	at scala.reflect.internal.tpe.TypeMaps$ErroneousCollector$.traverse(TypeMaps.scala:1167)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:114)
[error] 	at scala.reflect.internal.tpe.TypeMaps$ErroneousCollector$.traverse(TypeMaps.scala:1168)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$3(TypeMaps.scala:157)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:216)
[error] 	at scala.reflect.internal.tpe.TypeMaps$ErroneousCollector$.traverse(TypeMaps.scala:1168)
[......]
[error] 	at scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:111)
[error] 	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
[error] 	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
[error] 	at scala.tools.nsc.Global$$anon$4.inferImplicit(Global.scala:477)
[error] 	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
[error] 	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
[error] 	at scala.tools.nsc.Global$$anon$4.inferImplicitFor(Global.scala:477)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$applyImplicitArgs$2(Typers.scala:263)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:256)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:901)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:491)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1239)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1236)
[error] (izanami-server / Compile / compileIncremental) java.lang.StackOverflowError
[error] Total time: 17 s, completed Apr 24, 2019, 11:25:07 AM
```

Launching the same command 4 times seems to finish the compilation.

**Comment by larousso** [comment]
Hi, you have to configure sbt using SBT_OPTS=-Xmx2G -Xss20M -XX:MaxMetaspaceSize=512M
