### ISSUE TITLE
[error] izanami - Error publishing event to queue

### ISSUE THREAD

**Issue by sebprunier** [MAIF/izanami#286]
We get this kind of error since a few days :-(

Any help to solve this issue is welcome ! :-)

```
2019-09-09T12:19:42.151Z: [error] izanami - Error publishing event to queue
2019-09-09T12:19:42.151Z: at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
2019-09-09T12:19:42.151Z: at akka.actor.Actor.aroundReceive(Actor.scala:539)
2019-09-09T12:19:42.151Z: at akka.stream.impl.QueueSource$$anon$1.$anonfun$callback$1$adapted(QueueSource.scala:108)
2019-09-09T12:19:42.151Z: at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
2019-09-09T12:19:42.151Z: at akka.stream.impl.QueueSource$$anon$1.bufferElem(QueueSource.scala:101)
2019-09-09T12:19:42.151Z: java.lang.IllegalStateException: You have to wait for the previous offer to be resolved to send another request
2019-09-09T12:19:42.151Z: at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:481)
2019-09-09T12:19:42.152Z: at akka.actor.Actor.aroundReceive$(Actor.scala:537)
```

**Comment by larousso** [comment]
What kind of event store are you using ? Is it redis ?

**Comment by sebprunier** [comment]
Yes, we use Redis as the main datastore (`IZANAMI_DATABASE` and `IZANAMI_EVENT_STORE `).

We also use Elasticsearch for the Experiments datastore (`EXPERIMENT_EVENT_DATABASE` and `EXPERIMENT_VARIANT_BINDING_DATABASE`), but we have no more experiments in progress.

Izanami version is `1.5.0`

**Comment by pierrebruninmaif** [comment]
#472
