### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by deathtiny42** [MAIF/izanami#500]
I've downloaded `izanami.jar` and tried to start it with Java 1.8.0_212 and 12.0.1, but I receive in both cases the following error when I try to go on `localhost:9000`: 

```
[error] izanami - Error serving request GET /login
play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.NoClassDefFoundError: buildinfo/BuildInfo$]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:331)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:253)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:424)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:420)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: buildinfo/BuildInfo$
	at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:384)
	at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
	at scala.util.Try$.apply(Try.scala:210)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:199)
	at play.api.libs.streams.FlattenedAccumulator.$anonfun$run$2(Accumulator.scala:216)
Caused by: java.lang.NoClassDefFoundError: buildinfo/BuildInfo$
	at controllers.HomeController.generateIndex(HomeController.scala:65)
	at controllers.HomeController.$anonfun$login$1(HomeController.scala:51)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at controllers.actions.AuthAction.invokeBlock(actions.scala:40)
	at controllers.actions.AuthAction.invokeBlock(actions.scala:29)
	at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
	at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
	at scala.util.Try$.apply(Try.scala:210)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
Caused by: java.lang.ClassNotFoundException: buildinfo.BuildInfo$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at controllers.HomeController.generateIndex(HomeController.scala:65)
	at controllers.HomeController.$anonfun$login$1(HomeController.scala:51)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at controllers.actions.AuthAction.invokeBlock(actions.scala:40)
	at controllers.actions.AuthAction.invokeBlock(actions.scala:29)
	at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379) 
```

Hope you can help, I want to try this out! 
Thanks.

**Comment by deathtiny42** [comment]
I've tried downloading v1.8.2, and it works. So there must be something wrong in the latest release.

**Comment by deathtiny42** [comment]
I've finally tested v1.7.2 and this one works fine (for now)

**Comment by SoerenSilkjaer** [comment]
I assume this is related to #474
